### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by LittleTerry** [AlexPerathoner/YT-Chapters-Downloader#1]
I did exactly what you say in readme, but it turns out;

Traceback (most recent call last):
  File "C:/Users/Terry/PycharmProjects/exercise/YT_download/YT_Chapters_Downloader.py", line 73, in <module>
    j = json.loads(os.popen('youtube-dl -j ' + url).read())
  File "C:\ProgramData\Miniconda3\envs\autopy\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\ProgramData\Miniconda3\envs\autopy\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\ProgramData\Miniconda3\envs\autopy\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AlexPerathoner** [comment]
Hi!
First of all, thanks for using this little script of mine.
Does this happen with any video you tried? If not, could you please the link of the video you are using the script with?
I'll take a look at it as soon as possible (Tuesday, in the worst case).

**Comment by LittleTerry** [comment]
> Hi! First of all, thanks for using this little script of mine. Does this happen with any video you tried? If not, could you please the link of the video you are using the script with? I'll take a look at it as soon as possible (Tuesday, in the worst case).

Hi, Alex, thanks for your reply.  I used this command

python yt.py https://www.youtube.com/watch?v=5kzFCGE_2Y0

I renamed your file as yt.py
But... it looks like the bug is... unstable... Today it gave me:

![image](https://user-images.githubusercontent.com/19617725/151698637-4598420f-77f8-43d0-9908-37342f7229be.png)

And there are two new files in my folder, but I can't open the first, it's empty.
![image](https://user-images.githubusercontent.com/19617725/151698674-26b973b2-0dd8-4f61-a54f-89c261150407.png)

**Comment by AlexPerathoner** [comment]
Hi!
Apparently there was an [issue](https://github.com/pytube/pytube/issues/1060) with the module Pytube.
You can fix it by running: `python -m pip install git+https://github.com/Zeecka/pytube@fix_1060`.

Note that this script was initially intended to be used to download videos with multiple chapters ([like this one](https://www.youtube.com/watch?v=b1Fo_M_tj6w)). However, I just updated it to download videos without chapters as well.

I'll leave this issue open, in case some other encounter the same error.
